name: Generate CV

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install deps
        run: npm install

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Generate PDF
        run: npm run cv
        env:
          PUBLIC_SANITY_PROJECT_ID: ${{ secrets.PUBLIC_SANITY_PROJECT_ID }}
          PUBLIC_SANITY_DATASET: ${{ secrets.PUBLIC_SANITY_DATASET }}
          SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}

      - name: Commit PDF to branch cv
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout -B cv
          mv cv-aitor-ca.pdf cv-aitor-ca.pdf
          mv cv-aitor-es.pdf cv-aitor-es.pdf
          mv cv-aitor-en.pdf cv-aitor-en.pdf
          git add cv-aitor-*.pdf
          git commit -m "Update CV" || echo "No changes"
          git push --force origin cv
