name: Generate and Upload CVs

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Generate PDFs
        run: npm run cv
        env:
          PUBLIC_SANITY_PROJECT_ID: ${{ secrets.PUBLIC_SANITY_PROJECT_ID }}
          PUBLIC_SANITY_DATASET: ${{ secrets.PUBLIC_SANITY_DATASET }}
          SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}

      - name: Upload PDFs to Vercel Blob
        uses: dartilesm/vercel-blob-action@v2
        with:
          source: "cv-aitor-ca.pdf"
          destination: "cv/cv-aitor-ca.pdf"
          read-write-token: ${{ secrets.BLOB_READ_WRITE_TOKEN }}

      - name: Upload ES PDF
        uses: dartilesm/vercel-blob-action@v2
        with:
          source: "cv-aitor-es.pdf"
          destination: "cv/cv-aitor-es.pdf"
          read-write-token: ${{ secrets.BLOB_READ_WRITE_TOKEN }}

      - name: Upload EN PDF
        uses: dartilesm/vercel-blob-action@v2
        with:
          source: "cv-aitor-en.pdf"
          destination: "cv/cv-aitor-en.pdf"
          read-write-token: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
