name: Generate CV

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # opcional: cada dia a les 6h

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install deps
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Generate PDF
        run: node generate-pdf.js

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cv
          path: cv-aitor.pdf

      - name: Commit PDF to branch cv
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout -B cv
          mv cv-aitor.pdf cv-aitor.pdf
          git add cv-aitor.pdf
          git commit -m "Update CV"
          git push --force origin cv
